'use strict';

exports.sectionNews.news1 = [{"title":"\nSanjeev Gupta, a life member of the Madhya Pradesh Cricket Association, has challenged Sourav Ganguly’s continuation as president of the BCCI.In an email to Ganguly and other officials on Sunday, Gupta said that the BCCI rulebook debars anyone nominated to the International Cricket Council (ICC) Board from functioning as president.Ganguly was included in the ICC Board as BCCI's representative soon after attending the Board meeting on March 28, and has since emerged a contender for the soon-to-be vacant post of ICC chairman.Gupta stated that according to Rule 14(9) of the BCCI constitution, “it is amply clear that as soon as you are nominated to ICC, your post as BCCI president will get vacated automatically forthwith”.Objection dismissedA BCCI official, however, dismissed Gupta’s objection. “The clause should come into effect only if an [BCCI] office-bearer is 'elected' to the ICC. Otherwise the BCCI will be forced to nominate someone other than an office-bearer, which will be ridiculous,” he said.Interestingly, an appeal made by BCCI in the Supreme Court makes no mention of clause 14(9).The appeal, filed by treasurer Arun Dhumal through Adv. Bina Madhavan on April 21, requests the Court to permit BCCI to “carry out the amendments to Rule Nos. 6.4, 6.5, 7.3, 15(3) & (4), 19(2) and 45 in the Constitution which have been approved in the Annual General Meeting held on 01.12.2019.”The appeal requests the Apex Court to separate tenures of office-bearers of BCCI and State associations before cooling-off comes into effect and also to curtail the powers of the CEO. According to the current rulebook, the CEO has extraordinary powers, which the current dispensation seeks to restrict.Also, the BCCI has appealed for the clause mandating Supreme Court approval for any amendment to the BCCI constitution to be done away with.\n"}];

exports.sectionNews.news2 = [{"title":"\nHyderabad is home to two carrom World Cup champions — K. Srinivas (men) and S. Appoorwa (women). Not surprisingly it could be the first city in Telangana which will see a sports body — Carrom Association of Telangana (CAT) — host a tournament in the post-lockdown scenario at the Fateh Maidan Indoor Stadium in the first week of June with no entry for spectators.Reason? “It is pretty simple. The size of the carrom board is 36 inches (three feet), players don’t come into physical contact with each other. They will not touch the board and a player sits at least one foot away from the board with enough space for his elbow to play the strokes,” said B.K. Haranath, founder-president of CAT, which was originally the Hyderabad Carrom Association since 1972, in a chat with\nThe Hindu\non Sunday.“Even otherwise, the prescribed definition of the competition boards is such there should be a distance of 10 feet from one light point to the other on the boards, which means the players on the adjacent boards will be at least five feet away from each other,” he says. “And, nearly 16 to 20 boards can be arranged for a tournament with no individual umpires for each board,” he added.“There will be a technical director, chief referee and the assistant chief referees positioned 15-feet away from the first row of boards to monitor the matches,” he said.“This way, in a ranking tournament we can host 80 matches in a day spanning nine hours,” he added.“Audience has never been an issue as except the carrom family there will not be many spectators, so they can be easily controlled,” said Haranath.In fact, CAT is also planning an innovative, online carrom tournament given its popularity cutting across sections.\n"}];

exports.sectionNews.news3 = [{"title":"\nICC Cricket Committee chairman Anil Kumble says the recommendation to ban saliva for shining the ball is only an interim measure and “things will go back to normal” once the pandemic is brought under control.The Kumble-led panel recommended a ban on saliva to minimise the risk of infection. On Friday, the ICC, in its guidelines for resumption of the game, also suggested a bar on the practice.“...this is only an interim measure. In a few months or a year’s time, I think things will go back to as normal as it can be,” Kumble told Star Sports show ‘Cricket Connected’. The ban on saliva has elicited mixed response from bowlers, who said it would come in the way of generating swing. But most have also acknowledged the health risk that it might pose.\n"}];

exports.sectionNews.news4 = [{"title":"\nMuch like his predecessors, the Indian football team’s head coach Igor Stimac has realised that no matter how effective the training inputs are, the National team falters when it comes to scoring.In an interview to news channel WION recently, the Croatian, looking back at his stint that began last May, said: “We have proved that we can change many things in a short time. It was not easy to change from a kick-and-chase style to a more possession-based football.”Stimac was not very happy with the returns from the World Cup qualification tournament. “We didn’t take our opportunities. I thought we could surprise Oman, but inexperience cost us. Though India is no longer the team that loses easy games, we are not scoring enough goals.”Stressing the need to reduce the number of foreign recruits in domestic teams, he said, “I feel depressed and tired at repeatedly saying we have to reduce the number of foreign players in Indian domestic football.“If the Government changes the citizenship regulations, we can get seven to eight players of Indian origin who are playing abroad and that would change our results dramatically.”\n"}];

exports.sectionNews.news5 = [{"title":"\nThe iconic Eden Gardens has escaped the wrath of Cyclone Amphan with only some minor damage.After taking stock of the damage caused to the stadium, which has hosted two World Cup finals (1987 ODI and 2016 T20) and the first pink-ball Test in the country, the Cricket Association of Bengal (CAB) top brass decided to consult its structural engineer to get a concrete idea about the cyclone’s impact.“We don’t think there is any major damage to the Eden, but we cannot take any chances. We will consult our structural engineer to look into the issues,” CAB president Avishek Dalmiya said. The pitch and outfield were largely unaffected.\n"}];

exports.sectionNews.news6 = [{"title":"\nA 100-second video, titled #dontrushchallenge and featuring some of the best shooters in the country, conveys a crisp message: “Aim at bad memories, and shoot it, coz nothing should stay for long.” It ends with a symbolic tearing of a coronavirus portrait!Apurvi Chandela appears first in the video, reading a book and quickly changing into her shooting gear. Elavenil Valarivan, Anjum Moudgil, Divyansh Singh Panwar, Manu Bhaker, Abhishek Verma, Anish Bhanwala, Arjun Babuta, Aishwary Pratap Singh Tomar and Shriyanka Sadangi are the others in the clip, each performing a task.The transition from one shooter to another has been done with imagination: one throws a glove, the other catches it; one gives a T-shirt and the other wears it...“This team is all about fun, hard work, crazy ideas! Loved working on this challenge and at the end, it is all about being positive and enjoying what you do,” wrote World championship silver medallist Anjum on her Instagram page.It was her idea to do the video with Panwar. “The British, Russian and Iran shooting teams had made videos which were posted by the ISSF. We also decided to make one,” said Apurvi.“We added a few more shooters before Shriyanka, Apurvi and I wrote the script. Everyone was asked to perform their part,” said Anjum, revealing that it took two days to put things together.“Everybody sent their videos before all of them were combined to make the final one,” said Anjum.The beautiful message — shoot the bad memories and start afresh — is apt for the times we live in.\n"}];

exports.sectionNews.news7 = [{"title":"\nAn astonishing performance in First Class cricket is fading from public memory as the protagonist’s name is often associated with Twenty20s.In the Duleep Trophy final of 2017 at Lucknow, Washington Sundar, then only 17, scalped 11 batsmen (six and five) and hit 88 and 42 for India Red against India Blue to become the first cricketer with 10-plus wickets and more than 100 runs in the summit clash of this prestigious competition.A performance that underlined Washington’s immense all-round potential.Back in trainingThe Chennai lad, looking at a fresh season with optimism, has resumed training at a local ground, accompanied by his father M. Sundar. However, he is now specifically focusing on batting.“I am confident about my bowling. I feel I have to concentrate on batting to get the best out of myself,” Washington told\nThe Hindu\non Saturday.Even as his father does the throw-downs, Washington plays strokes around the wicket. A natural with the willow, Washington was chosen for the India under-19 team as a top-order batsman. His highest Ranji score, 159 against Tripura, came as an opener.“I am essentially an opener, but when I joined the India under-19 team, Rahul Dravid Sir asked me to bat in the middle-order and bowl off-spin a lot more. I adjusted to the role,” he said.Washington then grabbed attention in the IPL with his calm and canny bowling in the PowerPlays and soon did the same for India in T20s.However, since he batted down the order, opportunities to sparkle with the willow were few and far between.In the TNPL, he has conjured up whirlwind efforts, cutting and pulling short-pitched deliveries and punching off his back-foot.AdaptingHe has also realised the need to adapt. “I know, for India, I could be coming in at No. 6 or 7 in Twenty20s. I enjoy the challenge and the sense of adventure in batting in these slots.”Washington does not want to create self-imposed pressure by setting goals. “I want to follow the process, tick the boxes, the rest will follow.”\n"}];

exports.sectionNews.news8 = [{"title":"\nTrack and field athletes will return to outdoor training on Monday after two months of being confined to their rooms, but focus will be entirely on their fitness regimens to avoid injury.Athletics Federation of India president Adille Sumariwalla told\nPTI\nthat all the athletes based at NIS-Patiala, SAI Centre in Bengaluru and Ooty will start “outdoor fitness” training from Monday.On May 17, the government permitted the use of stadia and sports complexes without spectators and under strict guidelines which allowed the athletes to return to outdoor training.Neeraj elatedStar javelin thrower Neeraj Chopra, who has qualified for the now postponed Tokyo Olympics, is elated that outdoor training will start from Monday. “I am feeling happy. At least something is starting even though it will be a slow beginning,” he said from NIS-Patiala, where he has been confined to his room since March 18.\n"}];

exports.sectionNews.news9 = [{"title":"\nAfter BWF’s condensed calendar invited criticism, secretary-general Thomas Lund said that it provided the best framework for the sport’s return under the present circumstances.“The list of 22 is only related to Grade 1 and Grade 2 tournaments. However, it is not expected that each player should play all tournaments,” Lund said\n.\n“Some will play more because they may not reach the final rounds, others will not as they play more matches in each tournament.”He stated that talks were on about BWF's strict mandatory player regulations. “We understand that it is not fair to expect athletes to play every tournament. An announcement on this will be made soon.”In the revised schedule, Syed Modi Open (Super 300) and Indonesian Open (Super 1000) clash, both scheduled to run from November 17 to 22. But Lund said they had no other option.“Tournaments at different levels typically appeal to different levels of players. And, in the process of revamping the calendar, it has been necessary to have some Super 100 or 300 tournaments played in the same weeks as higher level tournaments.”It is not expected that each player will play or should play all tournaments\n"}];

exports.sectionNews.news10 = [{"title":"\nHikaru Nakamura bounced back from 1-2 to beat Levon Aronian 3-2 in their first mini-match of the best-of-three quarterfinals in the Lindores Abbey Rapid Challenge on Saturday.Aronian won the first regular game and proved equal in the next two. In the fourth, Aronian needed a draw to prevail, but Nakamura fought back to win. In the Armageddon game, Nakamura again proved his superiority.In another clash, Yu Yangyi beat Ding Liren 3-2.\n"}];

exports.sectionNews.news11 = [{"title":"\nBayern Munich beat Eintracht Frankfurt 5-2 on Saturday, surviving a brief second-half comeback scare, to stay four points clear of Borussia Dortmund at the top of the Bundesliga with seven games left to play.The Bavarians thought they had the match wrapped up after efforts from Leon Goretzka, Thomas Mueller and Robert Lewandowski had given them a 3-0 lead in the empty Allianz Arena.RattledEintracht defender Martin Hinteregger caught the Bayern defence napping to strike twice in three minutes and inject new life into the encounter.Yet the visitors then quickly gave away two goals — with Alphonso Davies pouncing on a defensive error on the hour and Hinteregger scoring an own goal in the 74th minute.\nThe results: Schalke 0 lost to Augsburg 3 (Loewen 5, Bazee 76, Cordova 90+1); Mainz 0 lost to Leipzig 5 (Werner 11, 48, 75, Poulsen 23, Sabitzer 36). Saturday: Bayern Munich 5 (Goretzka 17, Mueller 41, Lewandowski 46, Davies 61, Hinteregger 74-og) bt Eintracht Frankfurt 2 (Hinteregger 52, 55)\n.\n\n"}];

exports.sectionNews.news12 = [{"title":"\nClijsters determined to return to the US OpenKim Clijsters is looking forward to returning to the US Open. “If the US Open can happen, I want to be ready. I would be happy if I had to play on Court 18. I don’t have to be out on Arthur Ashe.”AFP\n"}];

exports.sectionNews.news13 = [{"title":"\nGM Aravindh Chithambaram emerged champion in the main category of the PM-Cares Fund Play2Help online series chess tournament, organised by V. Raghav Srivathsav. The final edition will be held on May 31. Call 81870 93036 for details.\nFinal placings: Main category: 1. Aravindh Chithambaram, 2. Aradhya Garg, 3. Bharath Subramanian, 4. M.G. Gahan and 5. Mitrabha Guha; Best players: Women: Vyshnavi; Below Elo 2000: Aditya Gupta;\nBelow Elo 1600: Nirbhay. \nUnder-15: Boys: Pragyan Sriram; Girls: Manu Hasini. \n"}];

exports.sectionNews.news14 = [{"title":"\n‘Bicycle girl’ Jyoti to appear for CFI trials‘Bicycle girl’ Jyoti Kumari, who pedalled around 1,300km with her injured father from New Delhi to Darbhanga, will appear for the Cycling Federation of India (CFI) trials once the lockdown ends. “We will surely send her for the trials after the lockdown is lifted. She was enrolled in Class IX on Saturday. At the moment, we want her to complete her matriculation,” her father Mohan Paswan said.PTI\n"}];

