'use strict';

exports.sectionNews.news1 = [{"title":"\nAmid growing uncertainty on the number of flights allowed by different States at specific airports and the health protocols to be followed by passengers at each of them, the Ministry of Civil Aviation held a meeting on Sunday evening with airlines and airports to finalise routes that could be opened from Monday.“Except Andhra Pradesh which will start on 26/5 & West Bengal on 28/5, domestic flights will recommence across the country from tomorrow,” Civil Aviation Minister Hadeep Puri tweeted after the meeting.Fresh guidelinesWith all domestic (air/ rail/ inter-State bus) travel to resume from Monday, the Health Ministry has issued new guidelines for inter-State travel and international arrivals, stating that only COVID-asymptomatic domestic passengers/ international arrivals will be permitted with the advice that they shall self-monitor their health for 14 days. However, the Ministry also instructed States/UTs to develop their own protocol with regard to quarantine and isolation as per their assessment.With several States announcing a delay in opening airports or restricting the number of flights over apprehension of a spike in infections, there was a lack of clarity among airlines about destinations they could connect to as well as the number of flights they could operate.While Mumbai will restart operations from Monday, it will allow only 25 each of arrivals and departures, just a fourth of the flights the Centre said airlines (30% of regular flights) could operate to different airports. The decision to resume flights came just hours after Maharashtra Chief Minister Uddhav Thackeray said he had sought more time from the Civil Aviation Ministry to restart operations.West Bengal's Kolkata and Bagdogra airports have delayed re-opening until May 28 due to cyclone Amphan. The airports will see curtailed operations and allow only 10 arrivals and departures each to begin with. Chief Minister Mamata Banerjee said on Saturday they would request the Centre to postpone domestic flights.Vijayawada and Visakhapatnam airports in Andhra Pradesh will reopen only from Tuesday, with only 20% of flights permitted. Hyderabad airport in Telangana will reopen but permit only 15 arrivals and departures.In a late night announcement, Mr. Puri said a maximum of 25 flights per day will land in Chennai, while there was no limit on departures. The State government, which had earlier indicated that it would allow departures rather than arrivals, was yet to announce its “quarantine” measures for in-coming passengers.\n"}];

exports.sectionNews.news2 = [{"title":"\nDeath of COVID-19 patients in Telangana crossed a grim milestone of 50 on Sunday. Four more people suffering from the infectious disease have died taking the toll to 53. The number of coronavirus positive cases too continued to rise as 41 more samples tested positive for the virus on Sunday.This is the sixth consecutive day that the deaths have been reported. After a lull of five days till May 18, the deaths have been on an upward trajectory from May 19. Among the COVID-19 patients whose death was reported on Sunday includes a 75-year-old man from Jagtial, a 72-year-old woman, a 60-year-old man who suffered from Severe Acute Respiratory Infection (SARI) too, and a 48-year-old woman who was also having Leukemia. The latter three are from Hyderabad.Though the numbers are alarming, Superintendent of Gandhi Hospital M. Raja Rao said that not everyone with co-morbidities such as hypertension, diabetes and other such diseases die. Around 40% of the total patients have health complications.“It is people with co-morbidities along with organ dysfunction who died. However, there are around 8-10 such cases who have recovered too. Besides, people with co-morbidities who were in intensive care unit (ICU) too have recovered,” Dr. Rao said.Migrant cases riseOf the 41 new cases reported on Sunday — 23 cases are from Greater Hyderabad Municipal Corporation limits and one is from neighbouring Rangareddy district, there are 11 migrants and 6 foreign evacuees.There has been steady increase in the number of migrants who tested positive.It is learnt that most of them have returned from Maharashtra. Till date, at least 130 of them have been detected with COVID-19. Officials said that their contacts are being traced.Till date, a total of 1,854 cases have been reported from Telangana. Out of them, 709 are active cases, 1092 were discharged, and 53 people died. The number of active cases, which dipped to below 400 till May 13, is on the rise. It now stands at 709.\n"}];

exports.sectionNews.news3 = [{"title":"\nAt a time when thousands of people are stranded across the country due to the ongoing COVID-19 lockdown, Chhattisgarh High Court Chief Justice P.R. Ramachandra Menon has quietly helped scores of medical and nursing students of AIIMS Raipur travel home.Chief Justice Menon’s timely intervention, on the basis of an email received from a Supreme Court lawyer, saw the State government swing into action to provide buses for the students to return to their hometowns in Kerala.Justice Menon, speaking to\nThe Hindu\non Sunday, said these students were tomorrow’s frontline workers in case of a future health crisis and they should be able to trust the system to help them in their need of hour. “Let them be able to do their duty to society in the years to come,” he said in a telephonic conversation from Chhattisgarh.The email sent by advocate Haris Beeran on May 17 to Chief Justice Menon said the students were stranded in Raipur since March 20. Mr. Beeran said some of them had contacted him, seeking legal help to get home. He said trains were available from Delhi and Punjab, but none passed through Chhattisgarh.“I generated a file on the basis of this email and passed an administrative order calling forth information from the State government... I wanted to ascertain the facts on whether the students had enough food or whether they had been denied entry into their hostels. I instructed the Registrar General to collect the information through the Advocate General of the State... I wanted to see if there was any need to register a case on the judicial side...” the Chief Justice said.He said the State government reacted promptly by providing buses for the students. “Full credit goes to the Chhattisgarh government.” He said the judiciary simply played its part of taking cognisance of a concerned citizen’s representation.“We [the judiciary] cannot simply direct the government to do anything unless there is a breach on the part of the government,” the CJ drew the line.\n"}];

exports.sectionNews.news4 = [{"title":"\nIn two incidents in Bihar within a span of 24 hours, a special train from Haryana, carrying some 1,300 people home to the northeastern States, was attacked and 12 passengers on a bus from Madhya Pradesh were abused and threatened.The journey for the returnees from Haryana was incident-free until their train stopped at Danapur in Bihar early on Sunday morning. Trouble started when the passengers, mostly young persons from northeastern States, refused to let several people waiting on the platform into the train.Police inaction“We did not allow the people to board the special train because of the COVID-19 threat. At that they attacked the train and broke the windowpanes with sticks and stones,” reported Renponi Kithan, one of the passengers. Her co-travellers said the police remained mute spectators as the people hurled abuse and threatened to burn the train down. They also alleged that the police beat up some of the returnees on the train instead of disciplining the violent crowd.“This happened after we had spent more than 20 hours on the train without food and water,” said Franto Tohoi, another passenger. He added that the train, which was supposed to be a direct service, was making long halts at several stations. “At this rate, we don’t know when we will reach our destinations.”Subhanan Chandra, the chief spokesperson of Northeast Frontier Railway, said the matter had been raised with officials of the East Central Railway. “It was a minor issue [which] the security personnel handled. The train is on the move and is being escorted by the Railway Protection Force,” he said.CPRO of East Central Railway Rajesh Kumar told the media that there was a minor scuffle between passengers for seat at Danapur railway station. Amid the scuffle, someone had thrown a stone, breaking a window pane of the train. However, the train later left the station with security, he said.In the other incident, members of a group from Nagaland, who were returning home in a bus from Madhya Pradesh, said they were racially abused when they stopped in Bihar for food on Saturday. “Twelve of us had stopped by a roadside eatery when some men came up, hurled abuses and called us coronavirus,” said Mhathung Ezung, who worked at a wildlife lodge at the Pench National Park. He also said members of the group were denied the use of washrooms at a couple of petrol pumps on the way.\n"}];

exports.sectionNews.news5 = [{"title":"\nA young woman, who is an asymptomatic COVID-19 patient, got married here on Sunday. The bride and her relatives, who took part in the wedding, have been isolated.The Salem district administration had allowed the wedding on humanitarian grounds.According to officials, the woman and 11 of her family members from Chennai had travelled to Salem on May 21 for her wedding with a youth from Gengavelli, near Attur.Health officials had collected samples from the woman and other family members at the check-post and she tested positive on Saturday.Based on the test results, officials from the district administration and health department advised her to be in isolation and asked the family to postpone the wedding.But the family requested the officials to allow them to go ahead with the wedding as planned and promised to follow all safety guidelines.Since the patient was asymptomatic, she was isolated at one of the houses here and the District Collector permitted the wedding with a limited number of attendees, officials said.Isolation advisedAs many as 28 family members took part and post wedding, all members were advised to be in isolation in their homes for the next 28 days.Doctors from the Urban Primary Health Centre, health inspectors, revenue and police officials monitored the conduct of the wedding to ensure all safety guidelines were followed.\n"}];

exports.sectionNews.news6 = [{"title":"\nWith 130 COVID-19 positive cases on Sunday, the tally in Karnataka crossed the 2,000 mark. The total number of cases in the State now stands at 2,089. Of Sunday’s 130 cases, a majority was reported from Chickballapur district with 27. Yadgir district had the next highest number of cases with 24.Of the 130 cases, 105 were people who had come from other States. Of this, 100 of them had a travel history to Maharashtra. Two other cases were reported from people who had an international travel history.On Sunday, 46 patients were discharged bringing the total number of people discharged in the State to 654.Domestic travelOf the total 2,089 cases in Karnataka, the biggest source of infection has been domestic travel, with 1,025 cases having a history of domestic travel.Meanwhile, 790 people contracted the infection after they came in contact with people who tested positive, and 99 people had an international travel history.The Department of Health and Family Welfare has completed over two lakh tests in the State.As of Sunday, 2,06,313 samples were tested and of these, 2,01,978 were reported to be negative.Over the last couple of weeks, Karnataka has ramped up the number of daily tests. According to analysis by the State war room, Karnataka now stands third in the country for tests per a million population.The comparison has been done among States which have a population higher than 10 million. Karnataka has done 3,209 tests per a million population. Delhi stands first with 9,852 tests per million, while Andhra Pradesh has conducted 5,909 tests per million.\n"}];

exports.sectionNews.news7 = [{"title":"\nMany States are simply following the Union Health Ministry’s guidelines for arriving air passengers, but Karnataka will require travellers boarding from such “high-risk States” as Maharashtra, Delhi, Tamil Nadu, Gujarat, Rajasthan and Madhya Pradesh to undergo seven days of institutional quarantine on arrival in Bengaluru.As air travel resumes in the country on Monday, passengers will be tested for COVID-19 from the fifth to seventh day of arrival, a Karnataka official said. If they test negative, they will be asked to follow seven days of home quarantine. But exemptions have been given to pregnant women, children below 10 and others. Asymptomatic passengers arriving from other States will be asked to follow 14 days of home quarantine.In Kerala, flyers will undergo thermal screening once they exit the aircraft. Those found asymptomatic will be subjected to home quarantine for 14 days. Those found symptomatic will be rushed from airports to a COVID-19 care centre or hospital.Gujarat will not require quarantine for asymptomatic passengers. “We are following the government of India’s protocols for domestic travellers departing from or arriving at airports in Gujarat,” Secretary (Civil Aviation) Mamta Verma said.Though Tamil Nadu Chief Minister Edappadi K. Palaniswami had urged the Centre to defer in-coming flights, both departure and arrivals will resume from Monday. It is mandatory for all passengers flying into the State to register their details online after booking the ticket and apply for and obtain a T.N. ePASS onhttps://TNepass.tnega.org.\n"}];

exports.sectionNews.news8 = [{"title":"\nThe Capital on Sunday reported 508 new COVID-19 cases, taking the tally to 13,418. Thirty more deaths were also added to the official toll, the highest single-day jump so far, taking the total to 261.Not all of the 30 deaths were reported in the past 24 hours, said a heath bulletin issued by the Delhi government. It added that a total of 6,540 patients have recovered while 6,617 are undergoing treatment. The city has 86 containment zones.Meanwhile, the Delhi government has ordered all 117 private hospitals, and nursing homes with a bed capacity of 50 and more, to reserve at least 20% of their beds for COVID-19 patients.Earlier in the day, the Aam Aadmi Party (AAP) said it welcomed a recent decision by the Delhi High Court to not entertain a plea that questioned the accuracy of the death figures published by the city government. The party added that the BJP must now apologise for indulging in “baseless, motivated and malicious campaign”.“After hearing both sides, the High Court said that allegations against the accuracy of the death figures published by the Delhi government is absolutely baseless,” AAP MLA Raghav Chadha said, adding that the Death Audit Committee was a competent authority and the data published by the Delhi government was free from discrimination or fabrication.MLA recoversAAP MLA Vishesh Ravi, who had tested positive for COVID-19 on May 3, said he has finally tested negative after battling the virus for 22 days. The Karol Bagh MLA said he will now donate plasma to help other patients.\n"}];

exports.sectionNews.news9 = [{"title":"\nCoaching classes for NEET examination will begin from second week of June, School Education Minister K.A. Sengottaiyan said in Gobichettipalayam on Sunday.The Minister told media persons that 7,300 government school students would be trained for 35 days in nine colleges and coaching would begin from second week of June.He hoped that at least 100 students would clear NEET and get selected for medical courses.Asked whether all the Class 10 students would be declared as passed the exams, the Minister said that any decision would be taken only after paper valuation. He said that decision on reopening of schools would be taken at the appropriate time in consultation with the Chief Minister.\n"}];

exports.sectionNews.news10 = [{"title":"\nThe Army on Sunday “categorically denied” reports that Indian patrol teams had been detained by Chinese troops along the Line of Actual Control (LAC) in eastern Ladakh, during the current standoff.“There has been no detention of Indian soldiers at the borders. We categorically deny this,” Army spokesperson Colonel Aman Anand said, a day after reports referred to the alleged detention of Indian soldiers in three separate incidents.\n"}];

exports.sectionNews.news11 = [{"title":"\nThe 40-year-old Al-Qaeda operative who was deported from the United States on Wednesday is likely to be brought to Hyderabad in a couple of days from Amritsar.It is learnt that the Telangana police are going to accompany Ibrahim Zubair Mohammed’s family while he is being brought to the city from Amritsar where he is in a quarantine centre. Sources in the department said that investigators will question the Al-Qaeda operative for his various activities with the banned organisation in the US, where he was convicted for five years in 2015 for terror financing. “The quarantine rules have been diluted in his case for security,” a senior officer said.\n"}];

exports.sectionNews.news12 = [{"title":"\nIn two incidents in Bihar within a span of 24 hours, a special train from Haryana, carrying some 1,300 people home to the northeastern States, was attacked and 12 passengers on a bus from Madhya Pradesh were abused and threatened.The journey for the returnees from Haryana was incident-free until their train stopped at Danapur in Bihar early on Sunday morning. Trouble started when the passengers, mostly young persons from northeastern States, refused to let several people waiting on the platform into the train.“We did not allow the people to board the special train due to the COVID-19 threat. At that they attacked the train and broke the windows with sticks and stones,” said Renponi Kithan, one of the passengers.\n"}];

exports.sectionNews.news13 = [];

exports.sectionNews.news14 = [{"title":"\nThe High Court has directed that the LG Polymers plant in Visakhapatnam should be sealed and no one, including the company directors, be allowed to enter its premises. The court further directed that the surrendered passports of the company directors should not be released.\n"}];

exports.sectionNews.news15 = [{"title":"\nIndia on Sunday reported the highest single-day spike so far of 7,097 COVID-19 cases, taking the overall tally to 1,38,482, according to reports from the State Health Departments. The number of active cases stood at 76,858, while 57,605 people have recovered. The death toll crossed 4,000, with 150 new fatalities.Data from Johns Hopkins University show that the total number of cases in India has surpassed that of Iran (with 1,35,701 confirmed infections). India now has the 10th highest number of confirmed cases worldwide.Maharashtra reported a surge of 3,041 cases — its highest till date — to breach the 50,000-mark. The tally touched 50,231, while 58 more deaths saw the toll surge to 1,635. The number of cases in Gujarat rose to 14,063, with 394 new infections. With 29 new fatalities, the toll rose to 858.Meanwhile, the Union Health Ministry said the recovery rate in the country stood at 41.28%.“The testing capacity has been ramped up in both, and as on date, around 1,50,000 tests can be conducted every day,” said the Ministry release.\n"}];

exports.sectionNews.news16 = [{"title":"\nThe number of persons testing positive for COVID-19 infection in the city rose to 10,576 and the State reported 765 positive cases on Sunday.As on date, 16,277 persons have tested positive and the number of active cases (including those in isolation) stands at 7,839. On Sunday, the State tested 12,275 persons, taking the total number of samples tested to over 4.09 lakh.The number of infected children and the elderly crossed the 1,000-mark. As of Sunday, 1,003 children, aged below 12, tested positive. Sunday’s bulletin from the Directorate of Public Health included a child aged less than a month old. The number of elderly who are infected stood at 1,358.As many as 5,643 persons are undergoing treatment in isolation wards, while 833 persons have been discharged from various hospitals in the State, taking the total number of discharged persons to 8,324. Those tested include three international passengers and 44 passengers who returned from other States.International passengers, who tested positive, include one each from Dubai, the Philippines and London.Among returnees from within the country, 39 from Maharashtra, two from Delhi and one each from Karnataka, West Bengal and Kerala added to the positive tally of positive cases.Till date, a total of 111 persons succumbed to the infection, including eight on Sunday. All of them had several co-morbidities, including diabetes, hypertension, chronic kidney disease or morbid obesity.\n\nFour patients admitted to the Rajiv Gandhi Government General Hospital died of the infection and two patients in Stanley lost their lives. Two patients admitted to private hospitals died due to the infection on Sunday.According to the bulletin, 76 passengers who returned from other countries reported positive till date. This includes 36 who tested positive on return and 40 persons who tested negative on arrival, but turned positive during exit screening.Four districts, including Coimbatore, Dharmapuri, Namakkal and Tiruppur have no active cases.Of the 40 international returnees, 19 are from West Asia; eight returnees from England; seven from the Philippines and six are from the US.Among those who returned by train from various States, 19 tested positive while 3, 944 tested negative.The results of 1,174 samples are awaited. A total of 5,137 samples were lifted, health officials said. Testing of 648 samples was under way. Of the 4,09,615 samples that were lifted, 18,363 samples are repeat samples.\n(*Two deaths were cross notified to other states. One patient died after turning negative for infection)\n\n"}];

exports.sectionNews.news17 = [{"title":"\nCotton crop area rise to come with strict vigilThe decision of the State government to increase crop area of cotton by 10.55 lakh acres for farmers to be able to access its investment support through Rythu Bandhu in the ensuing season was likely to be implemented with a strict vigil on seed companies and dealers. Apart from keeping a close watch on spurious seed, government was said to focus on checking sale of banned Bollgard 3 cotton seed.\n"}];

exports.sectionNews.news18 = [{"title":"\nThe Chhindwara police have suspended two policemen for allegedly beating a drunk man with batons, in yet another instance of personnel thrashing people during the lockdown in Madhya Pradesh.\n"}];

exports.sectionNews.news19 = [{"title":"\nJammu and Kashimir observed subdued and low-key celebrations on the occasion of Id-ul-Fitr on Sunday because of the COVID-19 pandemic and the lockdown restrictions.\n"}];

exports.sectionNews.news20 = [{"title":"\nHeavy rain, accompanied by strong winds, that lashed the city on Sunday afternoon resulted in inundation and tree- fall in many neighbourhoods across the city. Residents of 10th Main, 6th Sector of HSR Layout and Banaswadi, among other areas, saw their homes flooded.\n"}];

exports.sectionNews.news21 = [{"title":"\nThe massive reverse migration of people from urban areas to villages ever since lockdown was imposed due to COVID-19 has put focus on the Attracting and Retaining Youth in Agriculture (ARYA) scheme of the Centre.\n"}];

exports.sectionNews.news22 = [{"title":"\nMSMEs across Tamil Nadu which will start operations on Monday expressed concern over manpower shortage and lack of orders from clients. On Sunday, the State govern- ment gave a green signal to 17 industrial estates to start functioning with 25% staff.\n"}];

exports.sectionNews.news23 = [{"title":"\nThe rising COVID-19 cases in Tamil Nadu has resulted in the increase in the number of containment zones, according to an extraordinary government gazette issued on Saturday. There are a total of 1,143containment zones in the State, with Chennai topping the list with 635.\n"}];

exports.sectionNews.news24 = [{"title":"\nTomato arrivals pick upThe Madanapalle revenue division, which is the largest tomato growing belt in Asia, is slowly witnessing an increase in arrivals of the produce at the agriculture markets during the last one week. On Sunday, the total arrivals at various markets in the division stood about 3,000 tonnes.\n"}];

exports.sectionNews.news25 = [{"title":"\nRTC likely to scale up its operations from June 1The APSRTC is likely to scale up its operations from June 1. Official sources said efforts were aimed at gradually increasing the number of buses in all categories to cater to the needs of the people.\n"}];

